### ISSUE TITLE
How to automate check for incompatible licenses?

### ISSUE THREAD

**Issue by fhg-isi** [wagenrace/license_scanner#9]
The tool LicenseCheck is able to check for incompatible licenses. Unfortunately, it does not seem to consider nested dependencies when using other build-systems then poetry:

https://github.com/FHPythonUtils/LicenseCheck/issues/42

=> Is there a way to combine license_scanner and LicenseCheck to

a) get a list of all licenses from license_scanner

b) use the lookup mechanisms of licensecheck to check if those licenses are compatible to the license of the project

**Comment by fhg-isi** [comment]
I created an example on how to use LicenseCheck in combination with license_scanner:

https://github.com/FHPythonUtils/LicenseCheck/issues/42#issuecomment-1653284759

**Comment by wagenrace** [comment]
LicenseCheck and license_scanner work from a different base.
LicenseCheck uses requirements to get a list
license_scanner uses all installed packages

I do like your idea and will try to add it to some documentation. Adding logic to say what license can or cannot be used requires more legal knowledge then I have :)
